chore: 테스트를 위한 cd 설정 1차 변경

diff --git a/.github/workflows/backend-cd-coli.yml b/.github/workflows/backend-cd-coli.yml
--- a/.github/workflows/backend-cd-coli.yml
+++ b/.github/workflows/backend-cd-coli.yml
@@ -3,10 +3,10 @@ name: backend-cd-coli
 on:
   push:
     branches:
-      - coli2
+      - coli
 
 env:
-  DOCKERHUB_REPOSITORY: ody-official
+  DOCKERHUB_REPOSITORY: cdtest
 
 jobs:
   build-and-push:
@@ -51,48 +51,48 @@ jobs:
 
       - name: Docker Image Build And Push
         run: docker build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-coli -f Dockerfile . --push
-
-  pull-and-deploy:
-    needs: build-and-push
-    runs-on: coli-test
-    steps:
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_PASSWORD }}
-
-      - name: Clean Up Legacy Image
-        run: |
-          docker compose down || true
-          docker rmi $(docker images -q) -f || true
-
-      - name: Docker Compose up
-        run: |
-          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
-          export DOCKERHUB_REPOSITORY=$DOCKERHUB_REPOSITORY
-          export PROD_MYSQL_PASSWORD=${{ secrets.PROD_MYSQL_PASSWORD }}
-          export JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_PASSWORD }}
-          export TAG=${{ github.sha }}-prod_v2
-          docker compose up -d
-
-      - name: Health Check with Retry
-        uses: nick-invision/retry@v2
-        with:
-          timeout_minutes: 1
-          max_attempts: 5
-          retry_wait_seconds: 6
-          command: |
-            response=$(curl -s https://prod.oody.site/actuator/health)
-            status=$(echo $response | jq -r '.status')
-            if [ "$status" = "UP" ]; then
-              echo "Status is UP. Continuing..."
-              exit 0
-            else
-              echo "Status is NOT UP."
-              exit 1
-            fi
-
-      - name: Check Docker Process
-        if: always()
-        run: docker ps
+#
+#  pull-and-deploy:
+#    needs: build-and-push
+#    runs-on: coli-test
+#    steps:
+#      - name: Login to Docker Hub
+#        uses: docker/login-action@v3
+#        with:
+#          username: ${{ secrets.DOCKERHUB_USERNAME }}
+#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+#
+#      - name: Clean Up Legacy Image
+#        run: |
+#          docker compose down || true
+#          docker rmi $(docker images -q) -f || true
+#
+#      - name: Docker Compose up
+#        run: |
+#          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
+#          export DOCKERHUB_REPOSITORY=$DOCKERHUB_REPOSITORY
+#          export PROD_MYSQL_PASSWORD=${{ secrets.PROD_MYSQL_PASSWORD }}
+#          export JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_PASSWORD }}
+#          export TAG=${{ github.sha }}-prod_v2
+#          docker compose up -d
+#
+#      - name: Health Check with Retry
+#        uses: nick-invision/retry@v2
+#        with:
+#          timeout_minutes: 1
+#          max_attempts: 5
+#          retry_wait_seconds: 6
+#          command: |
+#            response=$(curl -s https://prod.oody.site/actuator/health)
+#            status=$(echo $response | jq -r '.status')
+#            if [ "$status" = "UP" ]; then
+#              echo "Status is UP. Continuing..."
+#              exit 0
+#            else
+#              echo "Status is NOT UP."
+#              exit 1
+#            fi
+#
+#      - name: Check Docker Process
+#        if: always()
+#        run: docker ps
